server:
  port: 9100
endpoints:
  shutdown:
    enabled: true
  restart:
    enabled: true
management:
  security:
    enabled : false 
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      
logging:
  level:
    org.springframework.web: DEBUG
      
      